### ISSUE TITLE
NameError: name 'log_gname' is not defined

### ISSUE THREAD

**Issue by cnpcshangbo** [CII-BIRDS/girder-detection-ros#13]
docker-compose run dronekit_node
```
[INFO] [1615839929.801330]: vel_setpoint received: 0.10000000149011612
Moving left(-)/right(+), vel_set = 0.10000000149011612
[ERROR] [1615839929.813054]: bad callback: <function cb at 0x7fab0941e0>
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/topics.py", line 750, in _invoke_callback
    cb(msg)
  File "/root/catkin_cv_ws/src/girder-detection-ros/scripts/velocity_based_movement.py", line 113, in cb
    gf = open(log_gname, mode='a')
NameError: name 'log_gname' is not defined
```

**Comment by cnpcshangbo** [comment]
solved by https://github.com/CII-BIRDS/girder-detection-ros/commit/476b8a392de997c629da11cc2b207d00efd454d7
