### ISSUE TITLE
command not found: catkin

### ISSUE THREAD

**Issue by cnpcshangbo** [CII-BIRDS/girder-detection-ros#24]
```
 bo@450r4j  ~/code  zsh imu_tool.zsh                              ✔  774  23:27:50 
ERROR in config: Command requires a target workspace.
ERROR in config: Command requires a target workspace.
imu_tool.zsh:11: command not found: catkin
```

**Comment by cnpcshangbo** [comment]
```
bo@450r4j  /opt/ros/noetic  sudo apt-get install ros-noetic-catkin python-catkin-tools
[sudo] password for bo: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-noetic-catkin is already the newest version (0.8.10-1focal.20210423.221558).
ros-noetic-catkin set to manually installed.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 python-catkin-tools : Depends: python (< 2.8)
                       Depends: python (>= 2.7)
                       Depends: python-catkin-pkg (>= 0.2.9) but it is not installable
                       Depends: python-osrf-pycommon but it is not installable
                       Depends: python:any (>= 2.6.6-7~)
E: Unable to correct problems, you have held broken packages.
 bo@450r4j  /opt/ros/noetic  sudo apt-get install ros-noetic-catkin python3-catkin-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
ros-noetic-catkin is already the newest version (0.8.10-1focal.20210423.221558).
ros-noetic-catkin set to manually installed.
The following NEW packages will be installed:
  python3-catkin-tools
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 314 kB of archives.
After this operation, 810 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://packages.ros.org/ros/ubuntu focal/main amd64 python3-catkin-tools all 0.5.0-1 [314 kB]
Fetched 314 kB in 1s (584 kB/s)              
Selecting previously unselected package python3-catkin-tools.
(Reading database ... 437833 files and directories currently installed.)
Preparing to unpack .../python3-catkin-tools_0.5.0-1_all.deb ...
Unpacking python3-catkin-tools (0.5.0-1) ...
Setting up python3-catkin-tools (0.5.0-1) ...
Installing new version of config file /etc/bash_completion.d/catkin_tools-completion.bash ...
 bo@450r4j  /opt/ros/noetic  catkin                               ✔  782  23:31:48
Traceback (most recent call last):
  File "/usr/bin/catkin", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3254, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3237, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3266, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 584, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 901, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'osrf-pycommon>0.1.1' distribution was not found and is required by catkin-tools
 bo@450r4j  /opt/ros/noetic  
```

**Comment by cnpcshangbo** [comment]
```
 bo@450r4j  /opt/ros/noetic  pip3 install catkin-tools          1 ↵  785  23:37:09
Requirement already satisfied: catkin-tools in /usr/lib/python3/dist-packages (0.5.0)
Collecting osrf-pycommon>0.1.1
  Downloading osrf_pycommon-0.1.9-py3-none-any.whl (38 kB)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from osrf-pycommon>0.1.1->catkin-tools) (45.2.0)
Installing collected packages: osrf-pycommon
Successfully installed osrf-pycommon-0.1.9
 bo@450r4j  /opt/ros/noetic  catkin                               ✔  786  23:37:25
usage: catkin [-h] [-a] [--test-colors] [--version] [--force-color | --no-color]
              [build | clean | config | create | env | init | list | locate | profile]
              ...

Error: No verb provided.
 bo@450r4j  /opt/ros/noetic   
```
pip3 deals with dependencies better.
